### ISSUE TITLE
Group_capstone issue

### ISSUE THREAD

**Issue by kayjeee** [kayjeee/Group-capstone#21]
Two students
https://github.com/kayjeee/Group-capstone/projects/1

**Comment by addod19** [comment]
### Hi @kayjeee and @derrick1451, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the link provided is not sending us to the kanban board as required. Here is where the link directed us to as seen in the screenshot below
![Screenshot from 2023-05-29 13-40-36](https://github.com/kayjeee/Group-capstone/assets/46388113/ca4d9f7f-5bc3-4b50-b601-84487d6156bc)
 Here is what we are expecting
![Screenshot from 2023-05-29 13-41-30](https://github.com/kayjeee/Group-capstone/assets/46388113/3971633b-98ca-4bf5-82b1-42d8e525ef82)



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

# Hi @kayjeee & @derrick1451 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- All project cards exist ✔
- Proper template is used ✔

## Required Changes ♻️
- Kindly make to all cards are assigned to team members in a fair way: which means `Student A` in its title should always be assigned to the same student (and analogical for other students) this also applies to the group tasks.
- It should look like this in the end:
  ![image](https://github.com/kayjeee/Group-capstone/assets/104968236/68bd37c7-c664-4720-b534-8b98899f1bc5)
- You just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Davidosky007** [comment]
Hi @kayjeee @derrick1451 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All cards created 👍 
* Link to board working 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
